/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard/payments'
import { Route as DashboardInvoicesIndexRouteImport } from './routes/dashboard/invoices/index'
import { Route as DashboardClientsIndexRouteImport } from './routes/dashboard/clients/index'
import { Route as DashboardInvoicesCreateRouteImport } from './routes/dashboard/invoices/create'
import { Route as DashboardInvoicesInvoiceDetailsRouteImport } from './routes/dashboard/invoices/$invoiceDetails'
import { Route as DashboardClientsCreateRouteImport } from './routes/dashboard/clients/create'
import { Route as DashboardClientsClientDetailsRouteImport } from './routes/dashboard/clients/$clientDetails'
import { Route as DashboardInvoicesEditEditInvoiceIdRouteImport } from './routes/dashboard/invoices/edit/$editInvoiceId'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvoicesIndexRoute = DashboardInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardClientsIndexRoute = DashboardClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvoicesCreateRoute = DashboardInvoicesCreateRouteImport.update({
  id: '/invoices/create',
  path: '/invoices/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvoicesInvoiceDetailsRoute =
  DashboardInvoicesInvoiceDetailsRouteImport.update({
    id: '/invoices/$invoiceDetails',
    path: '/invoices/$invoiceDetails',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardClientsCreateRoute = DashboardClientsCreateRouteImport.update({
  id: '/clients/create',
  path: '/clients/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardClientsClientDetailsRoute =
  DashboardClientsClientDetailsRouteImport.update({
    id: '/clients/$clientDetails',
    path: '/clients/$clientDetails',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardInvoicesEditEditInvoiceIdRoute =
  DashboardInvoicesEditEditInvoiceIdRouteImport.update({
    id: '/invoices/edit/$editInvoiceId',
    path: '/invoices/edit/$editInvoiceId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clients/$clientDetails': typeof DashboardClientsClientDetailsRoute
  '/dashboard/clients/create': typeof DashboardClientsCreateRoute
  '/dashboard/invoices/$invoiceDetails': typeof DashboardInvoicesInvoiceDetailsRoute
  '/dashboard/invoices/create': typeof DashboardInvoicesCreateRoute
  '/dashboard/clients': typeof DashboardClientsIndexRoute
  '/dashboard/invoices': typeof DashboardInvoicesIndexRoute
  '/dashboard/invoices/edit/$editInvoiceId': typeof DashboardInvoicesEditEditInvoiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/clients/$clientDetails': typeof DashboardClientsClientDetailsRoute
  '/dashboard/clients/create': typeof DashboardClientsCreateRoute
  '/dashboard/invoices/$invoiceDetails': typeof DashboardInvoicesInvoiceDetailsRoute
  '/dashboard/invoices/create': typeof DashboardInvoicesCreateRoute
  '/dashboard/clients': typeof DashboardClientsIndexRoute
  '/dashboard/invoices': typeof DashboardInvoicesIndexRoute
  '/dashboard/invoices/edit/$editInvoiceId': typeof DashboardInvoicesEditEditInvoiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clients/$clientDetails': typeof DashboardClientsClientDetailsRoute
  '/dashboard/clients/create': typeof DashboardClientsCreateRoute
  '/dashboard/invoices/$invoiceDetails': typeof DashboardInvoicesInvoiceDetailsRoute
  '/dashboard/invoices/create': typeof DashboardInvoicesCreateRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/invoices/': typeof DashboardInvoicesIndexRoute
  '/dashboard/invoices/edit/$editInvoiceId': typeof DashboardInvoicesEditEditInvoiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/payments'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/auth'
    | '/dashboard/'
    | '/dashboard/clients/$clientDetails'
    | '/dashboard/clients/create'
    | '/dashboard/invoices/$invoiceDetails'
    | '/dashboard/invoices/create'
    | '/dashboard/clients'
    | '/dashboard/invoices'
    | '/dashboard/invoices/edit/$editInvoiceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/payments'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/auth'
    | '/dashboard'
    | '/dashboard/clients/$clientDetails'
    | '/dashboard/clients/create'
    | '/dashboard/invoices/$invoiceDetails'
    | '/dashboard/invoices/create'
    | '/dashboard/clients'
    | '/dashboard/invoices'
    | '/dashboard/invoices/edit/$editInvoiceId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/payments'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/clients/$clientDetails'
    | '/dashboard/clients/create'
    | '/dashboard/invoices/$invoiceDetails'
    | '/dashboard/invoices/create'
    | '/dashboard/clients/'
    | '/dashboard/invoices/'
    | '/dashboard/invoices/edit/$editInvoiceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invoices/': {
      id: '/dashboard/invoices/'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/clients/': {
      id: '/dashboard/clients/'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invoices/create': {
      id: '/dashboard/invoices/create'
      path: '/invoices/create'
      fullPath: '/dashboard/invoices/create'
      preLoaderRoute: typeof DashboardInvoicesCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invoices/$invoiceDetails': {
      id: '/dashboard/invoices/$invoiceDetails'
      path: '/invoices/$invoiceDetails'
      fullPath: '/dashboard/invoices/$invoiceDetails'
      preLoaderRoute: typeof DashboardInvoicesInvoiceDetailsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/clients/create': {
      id: '/dashboard/clients/create'
      path: '/clients/create'
      fullPath: '/dashboard/clients/create'
      preLoaderRoute: typeof DashboardClientsCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/clients/$clientDetails': {
      id: '/dashboard/clients/$clientDetails'
      path: '/clients/$clientDetails'
      fullPath: '/dashboard/clients/$clientDetails'
      preLoaderRoute: typeof DashboardClientsClientDetailsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invoices/edit/$editInvoiceId': {
      id: '/dashboard/invoices/edit/$editInvoiceId'
      path: '/invoices/edit/$editInvoiceId'
      fullPath: '/dashboard/invoices/edit/$editInvoiceId'
      preLoaderRoute: typeof DashboardInvoicesEditEditInvoiceIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardClientsClientDetailsRoute: typeof DashboardClientsClientDetailsRoute
  DashboardClientsCreateRoute: typeof DashboardClientsCreateRoute
  DashboardInvoicesInvoiceDetailsRoute: typeof DashboardInvoicesInvoiceDetailsRoute
  DashboardInvoicesCreateRoute: typeof DashboardInvoicesCreateRoute
  DashboardClientsIndexRoute: typeof DashboardClientsIndexRoute
  DashboardInvoicesIndexRoute: typeof DashboardInvoicesIndexRoute
  DashboardInvoicesEditEditInvoiceIdRoute: typeof DashboardInvoicesEditEditInvoiceIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardClientsClientDetailsRoute: DashboardClientsClientDetailsRoute,
  DashboardClientsCreateRoute: DashboardClientsCreateRoute,
  DashboardInvoicesInvoiceDetailsRoute: DashboardInvoicesInvoiceDetailsRoute,
  DashboardInvoicesCreateRoute: DashboardInvoicesCreateRoute,
  DashboardClientsIndexRoute: DashboardClientsIndexRoute,
  DashboardInvoicesIndexRoute: DashboardInvoicesIndexRoute,
  DashboardInvoicesEditEditInvoiceIdRoute:
    DashboardInvoicesEditEditInvoiceIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
